"""Resolving not null check in dependent orms

Revision ID: 75d7f6580e3f
Revises: ffd21c50a4a5
Create Date: 2026-05-20 14:57:00.887889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d7f6580e3f'
down_revision: Union[str, Sequence[str], None] = 'ffd21c50a4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cart', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_addresses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_addresses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cart', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
