"""added new column in menu_items

Revision ID: e299b25a6128
Revises: 9ab5197011a3
Create Date: 2026-05-05 10:40:47.990292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e299b25a6128'
down_revision: Union[str, Sequence[str], None] = '9ab5197011a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('image', sa.CHAR(length=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
