"""Added image column in restaurant table

Revision ID: f01151fe5d3e
Revises: e299b25a6128
Create Date: 2026-05-06 12:48:04.188707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01151fe5d3e'
down_revision: Union[str, Sequence[str], None] = 'e299b25a6128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'image')
    # ### end Alembic commands ###
