"""Resolving FK constraint for user id setting it as null in dependent table on delete

Revision ID: ffd21c50a4a5
Revises: f01151fe5d3e
Create Date: 2026-05-20 14:54:22.821897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd21c50a4a5'
down_revision: Union[str, Sequence[str], None] = 'f01151fe5d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_restaurant_id_fkey'), 'cart', type_='foreignkey')
    op.drop_constraint(op.f('cart_user_id_fkey'), 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'restaurants', ['restaurant_id'], ['restaurant_id'], ondelete='SET NULL', initially='IMMEDIATE', deferrable=True)
    op.create_foreign_key(None, 'cart', 'users', ['user_id'], ['user_id'], ondelete='SET NULL', initially='IMMEDIATE', deferrable=True)
    op.drop_constraint(op.f('user_addresses_user_id_fkey'), 'user_addresses', type_='foreignkey')
    op.create_foreign_key(None, 'user_addresses', 'users', ['user_id'], ['user_id'], ondelete='SET NULL', initially='IMMEDIATE', deferrable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_addresses', type_='foreignkey')
    op.create_foreign_key(op.f('user_addresses_user_id_fkey'), 'user_addresses', 'users', ['user_id'], ['user_id'], deferrable=True)
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key(op.f('cart_user_id_fkey'), 'cart', 'users', ['user_id'], ['user_id'], deferrable=True)
    op.create_foreign_key(op.f('cart_restaurant_id_fkey'), 'cart', 'restaurants', ['restaurant_id'], ['restaurant_id'], deferrable=True)
    # ### end Alembic commands ###
